{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service-chart.serviceAccountName" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "service-chart.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: Role
  name: {{ include "service-chart.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
